### PR TITLE
Add Rails4.2 and Rails5.1 support  and travis-ci tests settings.

### PR DESCRIPTION
**Pull request by starcharles**
This PR is mainly for issue #21 . Activerecord related bug in state_machine is annoyed me.

So
- changed long time unmaintained library, 'state_machine' to 'state_machines' libraries
- added .travis.yml to test in multiple ruby versions and Rails versions
- tests denoted the compatiblity for either rails 4.2, and 5.1( I didn't test Rails 3.)

If any misunderstang, please tell me for rather improvement.

Thanks

### CODE REVIEW

**Comment by starcharles** [comment]
if this PR is merged. PR #20 is already useless. So can be ignored or deleted.

**Comment by Sailias** [comment]
@starcharles thanks for this, I will review this before #20

**Comment by Sailias** [comment]
@starcharles As a side note, I'm extremely busy right now so I won't be able to review this for 7 days or so, but I won't forget about your pull request.  Thanks again for contributing.

**Comment by Sailias** [comment]
Rails 5.1 support in another branch

**Pull request closed without merging**
