### PR TITLE
Fix for Rails 5+

### PR DESCRIPTION
**Pull request by azeemh**
there were some deprecation warnings -- i want to use this in one of my projects, i currently use rails 5.1.1 and got it installed...

I edited the readme for my profile, please keep the donations and your address on yours etc, just hope you could merge this and also maybe help get it possible to make an app with it? i.e. what forms and views do i need to actually use this with a model? 

would like it if we can do that...

### CODE REVIEW

**Comment by Sailias** [comment]
@azeemh please change the Readme back to the original in your pull request and I will review this in a Rails 5 project.

**Comment by Sailias** [comment]
@azeemh you are continuing to update your branch with personal details that is affecting this pull request.  I am closing your pull request and will take a look at implementing your Rails 5 changes directly.

**Comment by azeemh** [comment]
i don't have any personal details except for :usd because i live in usa.

and i would love to just use the code in a project and build an admin for
payments. i'm not sure how to change the pull request i just wanted to
update the readme on my personal repo. can't you just merge the changes to
the migration but not the readme?

**Comment by Sailias** [comment]
@azeemh I've created a Rails 5.1 compatible branch, so changes to your pull request aren't necessary.  Thank you for your contribution. 

The branch is here: https://github.com/Sailias/bitcoin_payable/tree/releases/rails-5.1

I've also created a demo application here:

https://github.com/Sailias/bitcoin_payable_demo

You will notice the model's and controller's code is minimal.

**Pull request closed without merging**
